version: '3.2'
services:
  client:
    build: client
    depends_on:
      - server
    ports:
      - 80:${UPLOADER_UI_PORT}
    environment:
      API_SERVER_HOST: http://server:${UPLOADER_SERVER_PORT}
    volumes:
      - ${UPLOADER_LOG_DIR}/client:/logs
  server:
    build: server
    ports:
      - 3001:${UPLOADER_SERVER_PORT}
    volumes:
      - ${UPLOADER_FILES_DIR}/uploaded-files:/usr/src/app/data/uploads
      - ${UPLOADER_FILES_DIR}/tmp:/usr/src/app/data/tmp
      - ${UPLOADER_LOG_DIR}/server:/usr/src/app/logs
